use_frameworks!

target 'DropboxSync_Example' do
  pod 'DropboxSync', :path => '../'
end

target 'DropboxSync_Tests' do
  pod 'DropboxSync', :path => '../'

  pod 'Quick'
  pod 'Nimble'
end

post_install do |installer|
  installer.pods_project.targets.each  do |target|
      target.build_configurations.each  do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
   end
end
