#!/usr/bin/env bash
clear
xcodebuild test -workspace DropboxSync.xcworkspace -scheme DropboxSync-Example -destination 'platform=iOS Simulator,name=iPhone SE,OS=11.0.1' 2>/dev/null | xcpretty -t

# xctool \
#   -workspace DropboxSync.xcworkspace \
#   -scheme DropboxSync-Example \
#   run-tests -test-sdk iphonesimulator11.0
